apiVersion: v1
kind: ConfigMap
metadata:
  name: wonderlandkube-configmap
  namespace: wonderland-dev
data:
  application2.yaml: |+
    app:
      text: helloapptext
    server:
      servlet:
        context-path: /wonderlandkube
    spring:
      application:
        name: wonderworld
      datasource:
        username: root
        password: password
        url: jdbc:mysql://host.minikube.internal:4001/wonder_world
        driver-class-name: com.mysql.cj.jdbc.Driver
    kafka:
      server: host.minikube.internal:29092
      topics:
        regist: regist.topic
  mytestfile.txt: |+
    hello my friend




