apiVersion: v1
kind: ConfigMap
metadata:
  name: wonderlandkube-configmap
  namespace: wonderland-dev
data:
  application2.yaml: |+
    app.text=helloapptext
    server:
      servlet:
        context-path: /wonderland
    spring:
      application:
        name: wonderworld
      datasource:
        username: root
        password: password
        url: jdbc:mysql://localhost:4001/wonder_world
        driver-class-name: com.mysql.cj.jdbc.Driver
  mytestfile.txt: |+
    hello my friend




