spring:
  application:
    name: wonderworld
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:4001/wonder_world
    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  text: helloapptext
server:
  servlet:
    context-path: /wonderlandkube
kafka:
  server: localhost:29092
  topics:
    regist: regist.topic
